### ISSUE TITLE
Formatting Style

### ISSUE THREAD

**Issue by Jacoab** [kobejean/TwitterML#6]
Now that our project is getting larger I think we should come up with a good styling format for our code that we agree on.  I was thinking of the following format which is consistent with the tensor flow format:

- filenames: underscore case

- class names: camel case

- class methods/functions: underscore case

- variables: underscore case

- file description block comments: encase comments in """ """ 

- class/method description block comments: encase comments in # #

I can go through all the code and change the formatting to these conventions, I just want to make sure that you agree with all this.

**Comment by kobejean** [comment]
I'm glad you brought that up. It was starting to get a bit disorganized. For the class/method description though I would like to actually use the """ """ style in addition to the file description block comments because I just learned that when you call help(class/method) it will actually print you the description that is encased in """ """. This link will probably show you better what I'm talking about: http://stackoverflow.com/questions/21930035/how-to-write-help-description-text-for-python-functions. All of the other format things are exactly how I would redo it.

**Comment by Jacoab** [comment]
So are you saying we should use the """ """ style for class/method description block comments and the 
# # style file description block comments, or use """ """ for all block comments?

**Comment by Jacoab** [comment]
So are you saying we should use the """ """ style for the class/methods blocks and the # # style for the file description blocks, or should we use """ """ for all block comments?

**Comment by kobejean** [comment]
Yeah especially the file/class/method descriptions because you can use the help command on them but I guess if we are going that far we might as well use """ """ for all block commands.

**Comment by Jacoab** [comment]
Ok, i'll go through the files here in a bit and change everything to the style we set up here.  As soon as I do that, i'll commit the changes to my branch and request a review from you before pushing it to the development branch.

**Comment by kobejean** [comment]
Ok cool thanks! Btw if you haven't checked it out already here is the link to the shakespeare text generation code: https://github.com/martin-gorner/tensorflow-rnn-shakespeare.
